apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: apigee-proxy-deployer
  namespace: argo
spec:
  # USES WORKLOAD IDENTITY: KSA 'argo-workflow' must be bound to your GSA
  serviceAccountName: argo-workflow 
  entrypoint: main
  
  # 1. Define the Shared Volume
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  templates:
    - name: main
      inputs:
        parameters:
          - name: repo_url
          - name: proxy_name
          - name: apigee_env
      dag:
        tasks:
          - name: clone-code
            template: git-clone
            arguments:
              parameters:
                - name: url
                  value: "{{inputs.parameters.repo_url}}"

          - name: maven-deploy
            dependencies: [clone-code]
            template: apigee-deploy
            arguments:
              parameters:
                - name: apigee_env
                  value: "{{inputs.parameters.apigee_env}}"

    # STEP 1: AUTHENTICATED GIT CLONE
    - name: git-clone
      inputs:
        parameters:
          - name: url
      container:
        image: alpine/git:latest
        workingDir: /src
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-creds
                key: token      # Corrected key name
          - name: GITHUB_USER
            valueFrom:
              secretKeyRef:
                name: github-creds
                key: username
        command: [sh, -c]
        args: 
          - |
            set -e
            echo "--- Cleaning workspace volume ---"
            # Delete hidden files too (like .git) to ensure fresh clone
            rm -rf ./* .[a-zA-Z]* || true
            
            echo "--- Cloning repository ---"
            # Strip https:// protocol if present to avoid duplication
            REPO_PATH=$(echo "{{inputs.parameters.url}}" | sed 's~https://~~')
            
            # Clone into current directory (.)
            git clone "https://${GITHUB_USER}:${GITHUB_TOKEN}@${REPO_PATH}" .
        volumeMounts:
          - name: workdir
            mountPath: /src

    # STEP 2: APIGEE DEPLOYMENT
    - name: apigee-deploy
      inputs:
        parameters:
          - name: apigee_env
      container:
        image: maven:3.8.5-openjdk-11
        workingDir: /src
        command: [sh, -c]
        # FIX: Removed Python dependency. 
        # Using grep/cut to parse JSON is safer in minimal containers.
        args:
          - |
            set -e
            
            echo "--- 1. Fetching Workload Identity Token ---"
            TOKEN=$(curl -s -H "Metadata-Flavor: Google" \
              "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" \
              | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4)

            if [ -z "$TOKEN" ]; then 
              echo "Error: Token generation failed. Check Workload Identity setup."
              exit 1
            fi
            echo "Token generated successfully."

            echo "--- 2. Executing Maven Deployment to {{inputs.parameters.apigee_env}} ---"
            mvn clean install -P{{inputs.parameters.apigee_env}} \
              -Dtoken="$TOKEN" \
              -Dapigee.options=update \
              -Dapigee.config.options=none \
              -DskipTests=true
        volumeMounts:
          - name: workdir
            mountPath: /src
