apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: apigee-hybrid-deploy-
  namespace: argo
spec:
  entrypoint: main
  # SERVICE ACCOUNT: Required for Workload Identity (Keyless Auth)
  serviceAccountName: argo-workflow

  arguments:
    parameters:
      - name: repo-url
        value: "https://github.com/git-azeez/apigee-hybrid-mock.git"
      - name: repo-branch
        value: "main"
      - name: proxy-path
        value: "src/gateway/hello-world-mock"

  templates:
  # --- Main DAG (Directed Acyclic Graph) ---
  - name: main
    inputs:
      parameters:
        - name: repo-url
        - name: repo-branch
        - name: proxy-path
    dag:
      tasks:
      - name: deploy-proxy
        template: maven-build-step
        arguments:
          parameters:
            - name: repo-url
              value: "{{inputs.parameters.repo-url}}"
            - name: repo-branch
              value: "{{inputs.parameters.repo-branch}}"
            - name: proxy-path
              value: "{{inputs.parameters.proxy-path}}"

  # --- The Build Template ---
  - name: maven-build-step
    inputs:
      parameters:
        - name: repo-url
        - name: repo-branch
        - name: proxy-path
      
      # ---------------------------------------------------------
      # STEP 1: GIT PULL
      # Argo automatically clones the repo before the container starts
      # ---------------------------------------------------------
      artifacts:
        - name: source-code
          path: /src
          git:
            repo: "{{inputs.parameters.repo-url}}"
            revision: "{{inputs.parameters.repo-branch}}"

    # ---------------------------------------------------------
    # STEP 2: MAVEN IMAGE
    # We use the official Maven Docker image to run the logic
    # ---------------------------------------------------------
    container:
      image: maven:3.9.6-eclipse-temurin-17
      workingDir: /src/{{inputs.parameters.proxy-path}}
      
      # ---------------------------------------------------------
      # STEP 3: MAVEN BUILD
      # We install dependencies and run the build command
      # ---------------------------------------------------------
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "--- [Setup] Installing Google Cloud SDK ---"
          # (Required because the standard Maven image doesn't have 'gcloud')
          apt-get update -qq && apt-get install -y -qq apt-transport-https ca-certificates gnupg curl > /dev/null
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list
          apt-get update -qq && apt-get install -y -qq google-cloud-cli > /dev/null

          echo "--- [Auth] Generating Token via Workload Identity ---"
          export TOKEN=$(gcloud auth print-access-token)
          
          if [ -z "$TOKEN" ]; then
             echo "Error: Failed to generate token. Check K8s Service Account binding."
             exit 1
          fi

          echo "--- [Build] Running Maven Deploy ---"
          mvn clean install \
            -Dbearer="$TOKEN" \
            -Dapigee.options=override
